---
- hosts: 127.0.0.1
  connection: local
  user: brian

  vars:
    username: "brian"

  roles:
    - common
    - ntp
    - dotfiles
    - googlechrome

- include: ../../linux-desktop-private/playbook.yml
