---
- name: check if Atom editor is installed
  stat: path=usr/bin/atom
  register: st

- name: Install PPA for Atom
  shell: "add-apt-repository ppa:webupd8team/atom"
# NOTE: apt_repository with ppa doesn't work on Linux Mint
#  apt_repository: repo="ppa:webupd8team/atom"
  sudo: true
  notify: apt-update
  when: not st.stat.exists

- name: Install Atom
  apt: pkg={{ item }}
  with_items:
    - atom
  sudo: true

- debug: msg="Atom already installed."
  when: st.stat.exists
