---
- name: check if Atom editor is installed
  stat: path=usr/bin/atom
  register: st

- name: Install Repo for Atom (deb)
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/atom/ubuntu trusty main"
  sudo: true
  notify: apt-update
  when: not st.stat.exists

- name: Install Repo for Atom (deb-src)
  apt_repository: repo="deb-src http://ppa.launchpad.net/webupd8team/atom/ubuntu trusty main"
  sudo: true
  notify: apt-update
  when: not st.stat.exists

- name: Install Atom
  apt: pkg={{ item }} force=yes
  with_items:
    - atom
  sudo: true

- debug: msg="Atom already installed."
  when: st.stat.exists
