---
- name: Check if Docker is installed
  stat: path=/usr/bin/docker
  register: st

- name: Add Docker repository key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  sudo: true
  when: not st.stat.exists

- name: Add Docker repository
  shell: echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
  sudo: true
  when: not st.stat.exists

- name: Docker apt-update
  apt: update_cache=yes
  sudo: true
  when: not st.stat.exists

- name: Install core packages
  apt: pkg={{item}} state=present
  with_items:
    - cgroup-lite
    - lxc
  sudo: true
  when: not st.stat.exists

- name: Install Docker
  apt: pkg=lxc-docker state=present
  sudo: true
  when: not st.stat.exists

- name: Check if Docker-Compose is installed
  stat: path=/usr/local/bin/docker-compose
  register: compose

- name: Install Docker-Compose (Fig)
  shell: /usr/bin/curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  sudo: true
  when: not compose.stat.exists

- name: Make Docker-Compose runnable
  file: path=/usr/local/bin/docker-compose owner={{username}} group={{username}} mode=u+x
  sudo: true
  when: not compose.stat.exists
