---
- name: Add Docker repository key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  sudo: true
- name: Add Docker repository
  shell: echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
  sudo: true
- name: Docker apt-update
  apt: update_cache=yes
  sudo: true

- name: Install core packages
  apt: pkg={{item}} state=present
  with_items:
    - cgroup-lite
    - lxc
  sudo: true

- name: Install latest Docker
  apt: pkg=lxc-docker state=present
  sudo: true
