---
- include: upgrade.yml

- name: Sudoers | update sudoers file and validate
  lineinfile: "dest=/etc/sudoers
              insertafter=EOF
              line='{{ username }} ALL=(ALL) NOPASSWD: ALL'
              regexp='^{{ username }}'
              state=present"
  sudo: true

- include: core_packages.yml
  sudo: true

- include: security.yml
  sudo: true

- include: vim.yml
- include: _gconf.yml
- include: rvm.yml
- include: nodejs.yml
- include: atom_editor.yml
- include: containers.yml
- include: lastpass.yml
